# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FastSparseFit_sparse <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_FastSparse_FastSparseFit_sparse', PACKAGE = 'FastSparse', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

FastSparseFit_dense <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_FastSparse_FastSparseFit_dense', PACKAGE = 'FastSparse', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

FastSparseCV_sparse <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_FastSparse_FastSparseCV_sparse', PACKAGE = 'FastSparse', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

FastSparseCV_dense <- function(X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs) {
    .Call('_FastSparse_FastSparseCV_dense', PACKAGE = 'FastSparse', X, y, Loss, Penalty, Algorithm, NnzStopNum, G_ncols, G_nrows, Lambda2Max, Lambda2Min, PartialSort, MaxIters, rtol, atol, ActiveSet, ActiveSetNum, MaxNumSwaps, ScaleDownFactor, ScreenSize, LambdaU, Lambdas, nfolds, seed, ExcludeFirstK, Intercept, withBounds, Lows, Highs)
}

cor_matrix <- function(p, base_cor) {
    .Call('_FastSparse_cor_matrix', PACKAGE = 'FastSparse', p, base_cor)
}

R_matrix_column_get_dense <- function(mat, col) {
    .Call('_FastSparse_R_matrix_column_get_dense', PACKAGE = 'FastSparse', mat, col)
}

R_matrix_column_get_sparse <- function(mat, col) {
    .Call('_FastSparse_R_matrix_column_get_sparse', PACKAGE = 'FastSparse', mat, col)
}

R_matrix_rows_get_dense <- function(mat, rows) {
    .Call('_FastSparse_R_matrix_rows_get_dense', PACKAGE = 'FastSparse', mat, rows)
}

R_matrix_rows_get_sparse <- function(mat, rows) {
    .Call('_FastSparse_R_matrix_rows_get_sparse', PACKAGE = 'FastSparse', mat, rows)
}

R_matrix_vector_schur_product_dense <- function(mat, u) {
    .Call('_FastSparse_R_matrix_vector_schur_product_dense', PACKAGE = 'FastSparse', mat, u)
}

R_matrix_vector_schur_product_sparse <- function(mat, u) {
    .Call('_FastSparse_R_matrix_vector_schur_product_sparse', PACKAGE = 'FastSparse', mat, u)
}

R_matrix_vector_divide_dense <- function(mat, u) {
    .Call('_FastSparse_R_matrix_vector_divide_dense', PACKAGE = 'FastSparse', mat, u)
}

R_matrix_vector_divide_sparse <- function(mat, u) {
    .Call('_FastSparse_R_matrix_vector_divide_sparse', PACKAGE = 'FastSparse', mat, u)
}

R_matrix_column_sums_dense <- function(mat) {
    .Call('_FastSparse_R_matrix_column_sums_dense', PACKAGE = 'FastSparse', mat)
}

R_matrix_column_sums_sparse <- function(mat) {
    .Call('_FastSparse_R_matrix_column_sums_sparse', PACKAGE = 'FastSparse', mat)
}

R_matrix_column_dot_dense <- function(mat, col, u) {
    .Call('_FastSparse_R_matrix_column_dot_dense', PACKAGE = 'FastSparse', mat, col, u)
}

R_matrix_column_dot_sparse <- function(mat, col, u) {
    .Call('_FastSparse_R_matrix_column_dot_sparse', PACKAGE = 'FastSparse', mat, col, u)
}

R_matrix_column_mult_dense <- function(mat, col, u) {
    .Call('_FastSparse_R_matrix_column_mult_dense', PACKAGE = 'FastSparse', mat, col, u)
}

R_matrix_column_mult_sparse <- function(mat, col, u) {
    .Call('_FastSparse_R_matrix_column_mult_sparse', PACKAGE = 'FastSparse', mat, col, u)
}

R_matrix_normalize_dense <- function(mat_norm) {
    .Call('_FastSparse_R_matrix_normalize_dense', PACKAGE = 'FastSparse', mat_norm)
}

R_matrix_normalize_sparse <- function(mat_norm) {
    .Call('_FastSparse_R_matrix_normalize_sparse', PACKAGE = 'FastSparse', mat_norm)
}

R_matrix_center_dense <- function(mat, X_normalized, intercept) {
    .Call('_FastSparse_R_matrix_center_dense', PACKAGE = 'FastSparse', mat, X_normalized, intercept)
}

R_matrix_center_sparse <- function(mat, X_normalized, intercept) {
    .Call('_FastSparse_R_matrix_center_sparse', PACKAGE = 'FastSparse', mat, X_normalized, intercept)
}

start_profiler <- function(str) {
    .Call('_FastSparse_start_profiler', PACKAGE = 'FastSparse', str)
}

stop_profiler <- function() {
    .Call('_FastSparse_stop_profiler', PACKAGE = 'FastSparse')
}

